//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Elegant.Ui.CommandSourceAttribute("MPTagThat.ApplicationCommands", "MPTagThat.ApplicationCommands")]

namespace MPTagThat
{
  //  This class is required for commands suppport.
// Do not modify this code inside the editor.

public class ApplicationCommands
  {

  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command Exit = new Elegant.Ui.Command("Exit");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command Save = new Elegant.Ui.Command("Save");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command Options = new Elegant.Ui.Command("Options");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command Refresh = new Elegant.Ui.Command("Refresh");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command Help = new Elegant.Ui.Command("Help");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command FileNameToTag = new Elegant.Ui.Command("FileNameToTag");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command TagFromInternet = new Elegant.Ui.Command("TagFromInternet");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command IdentifyFiles = new Elegant.Ui.Command("IdentifyFiles");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command SingleTagEdit = new Elegant.Ui.Command("SingleTagEdit");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command MultiTagEdit = new Elegant.Ui.Command("MultiTagEdit");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command GetCoverArt = new Elegant.Ui.Command("GetCoverArt");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command RemoveCoverArt = new Elegant.Ui.Command("RemoveCoverArt");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command GetLyrics = new Elegant.Ui.Command("GetLyrics");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command RemoveComment = new Elegant.Ui.Command("RemoveComment");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command RenameFiles = new Elegant.Ui.Command("RenameFiles");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command RenameFileOptions = new Elegant.Ui.Command("RenameFileOptions");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command CaseConversion = new Elegant.Ui.Command("CaseConversion");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command CaseConversionOptions = new Elegant.Ui.Command("CaseConversionOptions");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command OrganiseFiles = new Elegant.Ui.Command("OrganiseFiles");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command AutoNumber = new Elegant.Ui.Command("AutoNumber");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command ScriptExecute = new Elegant.Ui.Command("ScriptExecute");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command AddToBurner = new Elegant.Ui.Command("AddToBurner");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command AddToConversion = new Elegant.Ui.Command("AddToConversion");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command AddToPlaylist = new Elegant.Ui.Command("AddToPlaylist");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command RipStart = new Elegant.Ui.Command("RipStart");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command RipCancel = new Elegant.Ui.Command("RipCancel");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command DeleteAllTags = new Elegant.Ui.Command("DeleteAllTags");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command DeleteID3v1 = new Elegant.Ui.Command("DeleteID3v1");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command DeleteID3v2 = new Elegant.Ui.Command("DeleteID3v2");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command FolderSelect = new Elegant.Ui.Command("FolderSelect");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command ConvertStart = new Elegant.Ui.Command("ConvertStart");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command ConvertCancel = new Elegant.Ui.Command("ConvertCancel");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command BurnStart = new Elegant.Ui.Command("BurnStart");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command BurnCancel = new Elegant.Ui.Command("BurnCancel");
  [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible")]
  public static Elegant.Ui.Command ChangeDisplayColumns = new Elegant.Ui.Command("ChangeDisplayColumns");
}
}
